spring:
    application:
        name: eurka
    

server:
    port: 9001

eureka:
    instance:
        hostname: localhost
        prefer-ip-address: true
        status-page-url-path: /actuator/info #eureka注册中心的url link
        health-check-url-path: /actuator/health #健康检查的url
    client:
        registerWithEureka: false  #是否注册到注册中心
        fetchRegistry: false  #是否从注册中心拉取注册服务列表
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
